// src/utils/authFilters.js

export function getEmployeeRole(employee) {
  return employee?.profiles?.role || 'Employee';
}

export function filterEmployees(employees, user) {
  if (!user) return [];
  if (user.role === 'Admin' || user.role === 'Project Manager') return employees;
  
  // Employee can only see Employees, not PMs or Admins
  if (user.role === 'Employee') {
    return employees.filter(e => {
      const role = getEmployeeRole(e);
      return role === 'Employee';
    });
  }
  
  return employees;
}

export function filterProjects(projects, employees, user) {
  if (!user) return [];
  if (user.role === 'Admin' || user.role === 'Project Manager') return projects;

  // Find current user's employee record
  const userEmployee = employees.find(e => e.profile_id === user.id);
  const userEmpName = userEmployee?.name?.toLowerCase() || '';
  const userName = user.name?.toLowerCase() || '';

  // Get current user's assigned projects list
  const userAssignedProjects = (userEmployee?.assigned_projects || '')
    .split(',')
    .map(s => s.trim().toLowerCase())
    .filter(Boolean);

  return projects.filter(p => {
    const assignedNames = (p.assigned_employees || '')
      .split(',')
      .map(s => s.trim().toLowerCase())
      .filter(Boolean);

    // Rule: If current user is explicitly assigned, they can always see it
    const isProjectAssignedToUser = (p.project_code && userAssignedProjects.includes(p.project_code.toLowerCase())) ||
                                    (p.name && userAssignedProjects.includes(p.name.toLowerCase()));
    const isUserAssigned = (userEmpName && assignedNames.includes(userEmpName)) || 
                           (userName && assignedNames.includes(userName)) ||
                           isProjectAssignedToUser;
    if (isUserAssigned) return true;

    // If Employee: can only see projects assigned only to Employees
    if (user.role === 'Employee') {
      if (assignedNames.length === 0) return true;
      return true;
    }

    return true;
  });
}

export function filterNotifications(notifications, visibleProjects, visibleEmployees) {
  const visibleProjNames = new Set(visibleProjects.map(p => p.name.toLowerCase()));
  const visibleEmpNames = new Set(visibleEmployees.map(e => e.name.toLowerCase()));

  return notifications.filter(n => {
    const title = n.title || '';
    const message = n.message || '';

    // Workload Alert: check if employee name is in visibleEmployees
    if (title.startsWith('Workload Alert:')) {
      const empName = title.replace('Workload Alert:', '').trim().toLowerCase();
      return visibleEmpNames.has(empName);
    }

    // High-Risk Alert: check if project name is in visibleProjects
    if (title.startsWith('High-Risk Alert:')) {
      const projName = title.replace('High-Risk Alert:', '').trim().toLowerCase();
      return visibleProjNames.has(projName);
    }

    // Deadline Reminder: check if project name is in visibleProjects
    if (title.startsWith('Deadline Reminder:')) {
      const projName = title.replace('Deadline Reminder:', '').trim().toLowerCase();
      return visibleProjNames.has(projName);
    }

    // Weekly Report Ready: visible to PM/Admin, hidden for Employees
    if (title === 'Weekly Report Ready') {
      return false; // Typically generated by/for higher roles, filter out for standard list
    }

    // Fallback: search for mentions of visible projects or employees in message/title
    const lowerMsg = message.toLowerCase();
    const lowerTitle = title.toLowerCase();
    
    for (const projName of visibleProjNames) {
      if (lowerMsg.includes(projName) || lowerTitle.includes(projName)) return true;
    }
    for (const empName of visibleEmpNames) {
      if (lowerMsg.includes(empName) || lowerTitle.includes(empName)) return true;
    }

    return false;
  });
}
